//! The session editor's working state, framework-neutral.

use crate::config::{AuthMethod, PortForward, Secret, Session, SessionKind, SessionTrigger};

/// One row of the port-forwarding table while it is being edited.
///
/// Strings rather than numbers for the ports, because that is what a text field
/// holds: a half-typed port is a string that is not yet a number, and parsing it on
/// every keystroke to store a number would mean a field that cannot be empty.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PortForwardDraft {
    pub kind: String,
    pub name: String,
    pub bind_addr: String,
    pub bind_port: String,
    pub host: String,
    pub host_port: String,
}

/// One trigger row while it is being edited.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct TriggerDraft {
    pub expect: String,
    pub response: String,
    pub append_enter: bool,
    pub repeat: bool,
}

/// A session being written in a form.
///
/// This exists for the same reason [`TermSpan`][crate::terminal::TermSpan] and
/// [`TermMatch`][crate::terminal::TermMatch] do: the editor's state used to be a
/// type generated by the UI toolkit being decoupled from, so `session_models` —
/// which owns the rules for turning a form into a [`Session`] — named a toolkit
/// type. A second frontend could not reuse those rules at all, let alone build a
/// form to feed them.
///
/// Every field is a `String` (or `bool`/`i32`) rather than a parsed type, because a form
/// holds what was typed and not what it means: an empty host, a port mid-keystroke and a
/// name the user has not chosen yet are all legitimate states of an editor, and
/// [`SessionDraft::to_session`] is the one place that decides what they mean.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SessionDraft {
    /// The id being edited, or empty for a new session.
    pub id: String,
    pub name: String,
    /// `"ssh"`, `"serial"` or `"telnet"`; parsed leniently, like every other field.
    pub kind: String,
    pub host: String,
    pub port: i32,
    pub user: String,
    /// `"password"` or `"key"`.
    pub auth: String,
    /// Empty means "keep the saved password", never "no password" — a real secret is
    /// never echoed back into a form (#10, #276).
    pub password: String,
    pub private_key_path: String,
    /// Empty means "keep the saved key", for the same reason as `password`.
    pub private_key_inline: String,
    /// Whether the key is provided inline rather than by path.
    pub private_key_inline_mode: bool,
    pub proxy: String,
    /// The folder this session belongs to; empty is the default group.
    pub group: String,
    pub serial_port: String,
    pub baud_rate: i32,
    pub data_bits: i32,
    pub stop_bits: i32,
    pub parity: String,
    pub flow_control: String,
    pub encoding: String,
    pub vt100_drawing: bool,
    pub disable_shell_integration: bool,
    pub note: String,
    /// Another saved session to tunnel through, or empty for a direct connection.
    pub jump_session_id: String,
    /// Explicit bastion route, outermost first; the UI may reorder freely.
    pub jump_session_ids: Vec<String>,
    /// The port forwards, which the editor edits as rows rather than as the parsed
    /// config type.
    pub forwards: Vec<PortForwardDraft>,
    /// The expect/response triggers, for the same reason.
    pub triggers: Vec<TriggerDraft>,
}

impl SessionDraft {
    /// A draft for a brand-new SSH session, with the defaults the original form opens
    /// on.
    pub fn new_ssh() -> Self {
        Self {
            kind: SessionKind::Ssh.as_str().to_string(),
            port: 22,
            auth: AuthMethod::Password.as_str().to_string(),
            baud_rate: 115_200,
            data_bits: 8,
            stop_bits: 1,
            parity: "none".to_string(),
            flow_control: "none".to_string(),
            encoding: "utf-8".to_string(),
            vt100_drawing: true,
            ..Default::default()
        }
    }

    /// A draft filled from a saved session, for editing.
    ///
    /// The two secrets are deliberately left blank: a real password and a pasted private
    /// key are never read back into a form, so a saved value survives an edit only
    /// because an empty field means "unchanged" (#10, #276).
    pub fn from_session(session: &Session) -> Self {
        Self {
            id: session.id.clone(),
            name: session.name.clone(),
            kind: session.kind.as_str().to_string(),
            host: session.host.clone(),
            port: session.port as i32,
            user: session.user.clone(),
            auth: session.auth.as_str().to_string(),
            password: String::new(),
            private_key_path: session.private_key_path.clone(),
            private_key_inline: String::new(),
            private_key_inline_mode: !session.private_key_inline.is_empty(),
            proxy: session.proxy.clone(),
            group: session.group.clone(),
            serial_port: session.serial_port.clone(),
            baud_rate: session.baud_rate as i32,
            data_bits: session.data_bits as i32,
            stop_bits: session.stop_bits as i32,
            parity: session.parity.clone(),
            flow_control: session.flow_control.clone(),
            encoding: session.encoding.clone(),
            vt100_drawing: session.vt100_drawing,
            disable_shell_integration: session.disable_shell_integration,
            note: session.note.clone(),
            jump_session_id: session.jump_session_id.clone(),
            jump_session_ids: session.jump_session_ids.clone(),
            forwards: session
                .forwards
                .iter()
                .map(|forward| PortForwardDraft {
                    kind: forward.kind.clone(),
                    name: forward.name.clone(),
                    bind_addr: forward.bind_addr.clone(),
                    bind_port: forward.bind_port.to_string(),
                    host: forward.host.clone(),
                    host_port: forward.host_port.to_string(),
                })
                .collect(),
            triggers: session
                .triggers
                .iter()
                .map(|trigger| TriggerDraft {
                    expect: trigger.expect.clone(),
                    response: trigger.response.as_str().to_string(),
                    append_enter: trigger.append_enter,
                    repeat: trigger.repeat,
                })
                .collect(),
        }
    }

    /// The port forwards as the config type, dropping rows with no bind port.
    ///
    /// A row the user added but did not fill in is not an error to report: it is a row
    /// they abandoned, and keeping it would write a forward that binds nowhere.
    pub fn forwards(&self) -> Vec<PortForward> {
        self.forwards
            .iter()
            .filter_map(|draft| {
                let bind_port: u16 = draft.bind_port.trim().parse().ok()?;
                Some(PortForward {
                    kind: draft.kind.clone(),
                    name: draft.name.clone(),
                    bind_addr: draft.bind_addr.clone(),
                    bind_port,
                    host: draft.host.clone(),
                    host_port: draft.host_port.trim().parse().unwrap_or(0),
                })
            })
            .collect()
    }

    /// The triggers as the config type, dropping rows with no pattern.
    pub fn triggers(&self) -> Vec<SessionTrigger> {
        self.triggers
            .iter()
            .filter(|draft| !draft.expect.trim().is_empty())
            .map(|draft| SessionTrigger {
                expect: draft.expect.clone(),
                response: Secret::new(draft.response.clone()),
                append_enter: draft.append_enter,
                repeat: draft.repeat,
            })
            .collect()
    }

    /// The session this draft describes.
    ///
    /// `existing` is the saved session being edited, and it supplies the two secrets
    /// when their fields were left blank — the one thing a form cannot show, so the one
    /// thing it must not overwrite.
    ///
    /// A blank name is filled from what the session connects to, the way the original
    /// does: a session with no name is one the user did not care to name, and an empty
    /// row in the list is worse than an auto-generated one.
    pub fn to_session(&self, existing: Option<&Session>) -> Session {
        let password = if self.password.is_empty() {
            existing
                .map(|session| session.password.clone())
                .unwrap_or_default()
        } else {
            Secret::new(self.password.clone())
        };
        let private_key_inline = if self.private_key_inline_mode {
            if self.private_key_inline.is_empty() {
                existing
                    .map(|session| session.private_key_inline.clone())
                    .unwrap_or_default()
            } else {
                Secret::new(self.private_key_inline.clone())
            }
        } else {
            Secret::default()
        };
        let private_key_path = if self.private_key_inline_mode {
            String::new()
        } else {
            self.private_key_path.replace('\\', "/")
        };
        let kind = SessionKind::from_str(&self.kind);
        let auto_name = match kind {
            SessionKind::Serial => format!("{} @{}", self.serial_port, self.baud_rate),
            _ if self.user.trim().is_empty() => self.host.clone(),
            _ => format!("{}@{}", self.user, self.host),
        };
        let default_port = if kind == SessionKind::Telnet { 23 } else { 22 };

        Session {
            id: self.id.clone(),
            name: if self.name.is_empty() {
                auto_name
            } else {
                self.name.clone()
            },
            host: self.host.clone(),
            port: if self.port <= 0 {
                default_port
            } else {
                self.port as u16
            },
            user: self.user.clone(),
            auth: AuthMethod::from_str(&self.auth),
            password,
            private_key_path,
            private_key_inline,
            proxy: self.proxy.clone(),
            last_used: existing.and_then(|session| session.last_used.clone()),
            group: self.group.clone(),
            kind,
            local_distribution: existing
                .map(|session| session.local_distribution.clone())
                .unwrap_or_default(),
            local_working_dir: existing
                .map(|session| session.local_working_dir.clone())
                .unwrap_or_default(),
            serial_port: self.serial_port.clone(),
            baud_rate: if self.baud_rate <= 0 {
                115_200
            } else {
                self.baud_rate as u32
            },
            data_bits: if self.data_bits <= 0 {
                8
            } else {
                self.data_bits as u8
            },
            stop_bits: if self.stop_bits <= 0 {
                1
            } else {
                self.stop_bits as u8
            },
            parity: self.parity.clone(),
            flow_control: self.flow_control.clone(),
            encoding: self.encoding.clone(),
            vt100_drawing: self.vt100_drawing,
            forwards: self.forwards(),
            triggers: self.triggers(),
            disable_shell_integration: self.disable_shell_integration,
            note: self.note.clone(),
            jump_session_id: self.jump_session_id.clone(),
            jump_session_ids: self.jump_session_ids.clone(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A blank secret field means "keep what is saved", which is the whole reason the
    /// form does not echo a password back: an edit that touched nothing must not erase
    /// the credential (#10, #276).
    #[test]
    fn a_blank_password_keeps_the_saved_one() {
        let mut saved = Session::new_empty();
        saved.password = Secret::new("hunter2");
        // `Session` has no "inline mode" flag: a non-empty inline key *is* the mode,
        // which is why the draft derives it rather than storing a second copy.
        saved.private_key_inline = Secret::new("-----BEGIN KEY-----");

        let draft = SessionDraft::from_session(&saved);
        assert!(draft.password.is_empty(), "never echoed back");
        assert!(draft.private_key_inline.is_empty());
        assert!(draft.private_key_inline_mode, "derived from the saved key");

        let out = draft.to_session(Some(&saved));
        assert_eq!(out.password.as_str(), "hunter2");
        assert_eq!(out.private_key_inline.as_str(), "-----BEGIN KEY-----");
    }

    /// Typing a new secret replaces the old one, which is the other half of the same
    /// rule: "blank means keep" must not become "blank always wins".
    #[test]
    fn a_typed_password_replaces_the_saved_one() {
        let mut saved = Session::new_empty();
        saved.password = Secret::new("old");

        let mut draft = SessionDraft::from_session(&saved);
        draft.password = "new".to_string();
        assert_eq!(draft.to_session(Some(&saved)).password.as_str(), "new");
    }

    /// A new session with no name is named after what it connects to, because an empty
    /// row in the list is worse than an auto-generated one.
    #[test]
    fn a_blank_name_is_derived_from_the_target() {
        let mut draft = SessionDraft::new_ssh();
        draft.host = "example.com".to_string();
        draft.user = "root".to_string();
        assert_eq!(draft.to_session(None).name, "root@example.com");

        draft.user.clear();
        assert_eq!(draft.to_session(None).name, "example.com");
    }

    /// The port defaults per kind rather than to one number, because telnet is not ssh.
    #[test]
    fn a_blank_port_defaults_per_kind() {
        let mut draft = SessionDraft::new_ssh();
        draft.port = 0;
        assert_eq!(draft.to_session(None).port, 22);

        draft.kind = "telnet".to_string();
        assert_eq!(draft.to_session(None).port, 23);
    }

    /// A forward row the user abandoned is dropped rather than written as a listener
    /// that binds nowhere.
    /// A rule the user wrote has to come back the same way after a save and a reopen.
    ///
    /// This is the path the editor depends on and cannot test itself: it seeds its rows
    /// from [`SessionDraft::from_session`] and writes them back through
    /// [`SessionDraft::to_session`], and a rule that survived one but not the other would
    /// appear in the form and not in the file.
    #[test]
    fn a_forwarding_rule_survives_a_trip_through_the_form() {
        let mut draft = SessionDraft::new_ssh();
        draft.host = "example.com".to_string();
        draft.forwards = vec![PortForwardDraft {
            kind: "local".to_string(),
            name: "db".to_string(),
            bind_addr: "127.0.0.1".to_string(),
            bind_port: "18080".to_string(),
            host: "db.internal".to_string(),
            host_port: "5432".to_string(),
        }];
        let saved = draft.to_session(None);

        let reopened = SessionDraft::from_session(&saved);
        assert_eq!(reopened.forwards.len(), 1);
        assert_eq!(reopened.forwards[0].bind_port, "18080");
        assert_eq!(reopened.forwards[0].host, "db.internal");

        let again = reopened.to_session(Some(&saved));
        assert_eq!(again.forwards.len(), 1);
        assert_eq!(again.forwards[0].bind_port, 18080);
        assert_eq!(again.forwards[0].host_port, 5432);
        assert_eq!(again.forwards[0].name, "db");
    }

    /// Removing every rule and saving means having none.
    #[test]
    fn clearing_the_rows_clears_the_session_s_rules() {
        let mut draft = SessionDraft::new_ssh();
        draft.host = "example.com".to_string();
        draft.forwards = vec![PortForwardDraft {
            kind: "local".to_string(),
            bind_port: "8080".to_string(),
            host: "db.internal".to_string(),
            host_port: "5432".to_string(),
            ..Default::default()
        }];
        assert_eq!(draft.to_session(None).forwards.len(), 1);

        draft.forwards.clear();
        assert!(draft.to_session(None).forwards.is_empty());
    }

    #[test]
    fn an_unfilled_forward_row_is_dropped() {
        let mut draft = SessionDraft::new_ssh();
        draft.forwards = vec![
            PortForwardDraft {
                kind: "L".to_string(),
                bind_port: "8080".to_string(),
                host: "db.internal".to_string(),
                host_port: "5432".to_string(),
                ..Default::default()
            },
            // No bind port: half-typed, or abandoned.
            PortForwardDraft {
                kind: "L".to_string(),
                ..Default::default()
            },
        ];
        let forwards = draft.to_session(None).forwards;
        assert_eq!(forwards.len(), 1);
        assert_eq!(forwards[0].bind_port, 8080);
        assert_eq!(forwards[0].host, "db.internal");
    }

    /// A trigger with no pattern matches nothing, so it is not a rule.
    #[test]
    fn a_trigger_with_no_pattern_is_dropped() {
        let mut draft = SessionDraft::new_ssh();
        draft.triggers = vec![
            TriggerDraft {
                expect: "Password:".to_string(),
                response: "hunter2".to_string(),
                append_enter: true,
                repeat: false,
            },
            TriggerDraft {
                response: "ignored".to_string(),
                ..Default::default()
            },
        ];
        let triggers = draft.to_session(None).triggers;
        assert_eq!(triggers.len(), 1);
        assert_eq!(triggers[0].expect, "Password:");
        assert_eq!(triggers[0].response.as_str(), "hunter2");
    }

    /// A round trip through the form keeps everything the form can show.
    #[test]
    fn a_session_survives_a_round_trip_through_the_form() {
        let mut saved = Session::new_empty();
        saved.id = "s1".to_string();
        saved.name = "prod".to_string();
        saved.host = "10.0.0.1".to_string();
        saved.port = 2222;
        saved.user = "deploy".to_string();
        saved.kind = SessionKind::Ssh;
        saved.auth = AuthMethod::Key;
        saved.private_key_path = "C:\\Users\\me\\.ssh\\id_ed25519".to_string();
        saved.group = "Alpha".to_string();
        saved.note = "nightly".to_string();

        let back = SessionDraft::from_session(&saved).to_session(Some(&saved));
        assert_eq!(back.id, "s1");
        assert_eq!(back.name, "prod");
        assert_eq!(back.host, "10.0.0.1");
        assert_eq!(back.port, 2222);
        assert_eq!(back.user, "deploy");
        assert_eq!(back.auth, AuthMethod::Key);
        assert_eq!(back.group, "Alpha");
        assert_eq!(back.note, "nightly");
        // Windows separators are normalised, because a saved path is used by a shell.
        assert_eq!(back.private_key_path, "C:/Users/me/.ssh/id_ed25519");
    }

    /// A trigger rule has to come back the same way after a save and a reopen.
    ///
    /// The same path the forwarding rules take, and the same reason for testing it here:
    /// the editor seeds its rows from `from_session` and writes them back through
    /// `to_session`, so a rule that survived one but not the other would appear in the
    /// form and not in the file.
    #[test]
    fn a_trigger_survives_a_round_trip_through_the_form() {
        let mut draft = SessionDraft::new_ssh();
        draft.host = "example.com".to_string();
        draft.triggers = vec![TriggerDraft {
            expect: "Password:".to_string(),
            response: "hunter2".to_string(),
            append_enter: true,
            repeat: false,
        }];
        let saved = draft.to_session(None);

        let reopened = SessionDraft::from_session(&saved);
        assert_eq!(reopened.triggers.len(), 1);
        assert_eq!(reopened.triggers[0].expect, "Password:");
        assert!(reopened.triggers[0].append_enter);
        assert!(!reopened.triggers[0].repeat);

        let again = reopened.to_session(Some(&saved));
        assert_eq!(again.triggers.len(), 1);
        assert_eq!(again.triggers[0].response.as_str(), "hunter2");
    }

    /// Removing every trigger and saving means having none, exactly as for the forwards.
    #[test]
    fn clearing_the_trigger_rows_clears_the_session_s_triggers() {
        let mut draft = SessionDraft::new_ssh();
        draft.host = "example.com".to_string();
        draft.triggers = vec![TriggerDraft {
            expect: "Password:".to_string(),
            response: "hunter2".to_string(),
            ..Default::default()
        }];
        assert_eq!(draft.to_session(None).triggers.len(), 1);

        draft.triggers.clear();
        assert!(draft.to_session(None).triggers.is_empty());
    }
}
